REM ### **IF** YOUR COM PORT NUMBER IS GREATER
REM ### THAN 9, USE THE FOLLOWING SYNTAX:
REM ### FOR EXAMPLE, IF YOUR COM PORT IS COM22:
REM ### set COMPORT=\\.\COM22

REM ### CONFIGURE YOUR COM PORT HERE

set COMPORT=COM7

REM ### THE BELOW BAUD RATE MUST MATCH
REM ### YOUR TRANSCEIVER BAUD RATE!

mode %COMPORT% BAUD=38400 PARITY=n DATA=8 > NUL
